-- Generated by scripts/richmd-project — do not hand-edit.
-- Document-shell hook (richmd#25 / ADR-0023): the 4th consumer contract.
-- Renders the masthead (eyebrow, lede) and colophon (footer) from the
-- page-identity frontmatter design_doc.frontmatter_keys declares; each
-- region preserves the value's inline markup (links, bold) by reading the
-- raw doc.meta metavalue, never stringifying. The masthead region also
-- prepends the framework's semantic-look overlay as a projected <style>
-- block (ADR-0024) — richmd owns the base look, the framework the semantic
-- look. Structure is richmd-* region elements; richmd owns the base look.
local function meta_to_inlines(v)
  if v == nil then return nil end
  if type(v) == "string" then
    if v == "" then return nil end
    return pandoc.Inlines({ pandoc.Str(v) })
  end
  if type(v) == "table" then
    local inlines = {}
    for _, el in ipairs(v) do table.insert(inlines, el) end
    if #inlines == 0 then return nil end
    return pandoc.Inlines(inlines)
  end
  return nil
end

-- style_block() -> the framework semantic-look overlay as a
-- pandoc.RawBlock (ADR-0024). Delivered through the shell hook because
-- richmd exposes no consumer-stylesheet input; the masthead region
-- prepends it ahead of the page chrome. The CSS is SCHEMA-DERIVED
-- (per-kind, per-lens, per-tint) — a schema mutation reprojects it.
local function style_block()
  return pandoc.RawBlock(
    "html",
    "<style>\n" .. [==[
/* Framework semantic-look overlay — projected by scripts/richmd-project (ADR-0024). */
/* richmd owns the base look; this overlay owns the per-kind accent, per-lens */
/* pill palette, and card tints — the design's own vocabulary. It overrides */
/* cleanly: any base property it takes over is reset then restyled. */
    .richmd-doc {
      --fw-lens-modeling-bg: oklch(92% 0.05 130);
      --fw-lens-modeling-fg: oklch(38% 0.1 130);
      --fw-lens-depth-bg: oklch(92% 0.05 275);
      --fw-lens-depth-fg: oklch(38% 0.11 275);
      --fw-lens-composition-bg: oklch(91% 0.05 185);
      --fw-lens-composition-fg: oklch(34% 0.08 185);
      --fw-lens-state-bg: oklch(92% 0.045 315);
      --fw-lens-state-fg: oklch(38% 0.1 315);
      --fw-lens-invariants-bg: oklch(93% 0.06 80);
      --fw-lens-invariants-fg: oklch(40% 0.1 65);
      --fw-lens-robustness-bg: oklch(92% 0.05 20);
      --fw-lens-robustness-fg: oklch(42% 0.11 15);
      --fw-enf-mechanism-bg: oklch(91% 0.06 150);
      --fw-enf-mechanism-fg: oklch(35% 0.09 150);
      --fw-enf-partial-bg: oklch(93% 0.06 80);
      --fw-enf-partial-fg: oklch(40% 0.1 65);
      --fw-enf-convention-bg: oklch(93% 0.007 75);
      --fw-enf-convention-fg: oklch(52% 0.014 75);
      --fw-tint-teal-bg: oklch(94% 0.035 185);
      --fw-tint-teal-fg: oklch(34% 0.08 185);
      --fw-tint-teal-edge: oklch(70% 0.09 185);
      --fw-tint-violet-bg: oklch(94% 0.035 300);
      --fw-tint-violet-fg: oklch(38% 0.1 300);
      --fw-tint-violet-edge: oklch(70% 0.1 300);
      --fw-tint-amber-bg: oklch(94% 0.045 75);
      --fw-tint-amber-fg: oklch(40% 0.1 65);
      --fw-tint-amber-edge: oklch(75% 0.11 70);
      --fw-tint-blue-bg: oklch(94% 0.03 245);
      --fw-tint-blue-fg: oklch(38% 0.09 245);
      --fw-tint-blue-edge: oklch(70% 0.08 245);
      --fw-tint-rose-bg: oklch(94% 0.03 15);
      --fw-tint-rose-fg: oklch(42% 0.11 15);
      --fw-tint-rose-edge: oklch(72% 0.1 15);
      --fw-tint-slate-bg: oklch(94% 0.006 75);
      --fw-tint-slate-fg: oklch(38% 0.012 75);
      --fw-tint-slate-edge: oklch(87% 0.008 75);
      --fw-clause-given-ink: oklch(52% 0.014 75);
      --fw-clause-when-ink: oklch(52% 0.16 55);
      --fw-clause-then-ink: oklch(45% 0.11 185);
      --fw-level-interface-bg: oklch(93% 0.05 155);
      --fw-level-interface-fg: oklch(38% 0.09 155);
      --fw-behavior-bg: oklch(97.5% 0.014 245);
    }
    @media (prefers-color-scheme: dark) {
      .richmd-doc:not([data-richmd-theme="light"]) {
        --fw-lens-modeling-bg: oklch(30% 0.06 130);
        --fw-lens-modeling-fg: oklch(85% 0.08 130);
        --fw-lens-depth-bg: oklch(30% 0.06 275);
        --fw-lens-depth-fg: oklch(84% 0.07 275);
        --fw-lens-composition-bg: oklch(27% 0.05 185);
        --fw-lens-composition-fg: oklch(82% 0.07 185);
        --fw-lens-state-bg: oklch(29% 0.06 315);
        --fw-lens-state-fg: oklch(84% 0.07 315);
        --fw-lens-invariants-bg: oklch(30% 0.06 75);
        --fw-lens-invariants-fg: oklch(85% 0.08 75);
        --fw-lens-robustness-bg: oklch(29% 0.055 20);
        --fw-lens-robustness-fg: oklch(84% 0.07 20);
        --fw-enf-mechanism-bg: oklch(27% 0.055 150);
        --fw-enf-mechanism-fg: oklch(82% 0.08 150);
        --fw-enf-partial-bg: oklch(30% 0.06 75);
        --fw-enf-partial-fg: oklch(85% 0.08 75);
        --fw-enf-convention-bg: oklch(27% 0.008 75);
        --fw-enf-convention-fg: oklch(65% 0.01 75);
        --fw-tint-teal-bg: oklch(26% 0.04 185);
        --fw-tint-teal-fg: oklch(82% 0.07 185);
        --fw-tint-teal-edge: oklch(45% 0.08 185);
        --fw-tint-violet-bg: oklch(27% 0.045 300);
        --fw-tint-violet-fg: oklch(83% 0.07 300);
        --fw-tint-violet-edge: oklch(48% 0.09 300);
        --fw-tint-amber-bg: oklch(28% 0.05 75);
        --fw-tint-amber-fg: oklch(85% 0.08 75);
        --fw-tint-amber-edge: oklch(55% 0.1 70);
        --fw-tint-blue-bg: oklch(26% 0.035 245);
        --fw-tint-blue-fg: oklch(82% 0.06 245);
        --fw-tint-blue-edge: oklch(46% 0.07 245);
        --fw-tint-rose-bg: oklch(26% 0.035 15);
        --fw-tint-rose-fg: oklch(84% 0.07 15);
        --fw-tint-rose-edge: oklch(48% 0.08 15);
        --fw-tint-slate-bg: oklch(25% 0.008 75);
        --fw-tint-slate-fg: oklch(80% 0.008 75);
        --fw-tint-slate-edge: oklch(38% 0.012 75);
        --fw-clause-given-ink: oklch(70% 0.01 75);
        --fw-clause-when-ink: oklch(84% 0.11 70);
        --fw-clause-then-ink: oklch(82% 0.09 185);
        --fw-level-interface-bg: oklch(28% 0.055 155);
        --fw-level-interface-fg: oklch(84% 0.08 155);
        --fw-behavior-bg: oklch(26% 0.035 245);
      }
    }
    .richmd-doc[data-richmd-theme="dark"] {
      --fw-lens-modeling-bg: oklch(30% 0.06 130);
      --fw-lens-modeling-fg: oklch(85% 0.08 130);
      --fw-lens-depth-bg: oklch(30% 0.06 275);
      --fw-lens-depth-fg: oklch(84% 0.07 275);
      --fw-lens-composition-bg: oklch(27% 0.05 185);
      --fw-lens-composition-fg: oklch(82% 0.07 185);
      --fw-lens-state-bg: oklch(29% 0.06 315);
      --fw-lens-state-fg: oklch(84% 0.07 315);
      --fw-lens-invariants-bg: oklch(30% 0.06 75);
      --fw-lens-invariants-fg: oklch(85% 0.08 75);
      --fw-lens-robustness-bg: oklch(29% 0.055 20);
      --fw-lens-robustness-fg: oklch(84% 0.07 20);
      --fw-enf-mechanism-bg: oklch(27% 0.055 150);
      --fw-enf-mechanism-fg: oklch(82% 0.08 150);
      --fw-enf-partial-bg: oklch(30% 0.06 75);
      --fw-enf-partial-fg: oklch(85% 0.08 75);
      --fw-enf-convention-bg: oklch(27% 0.008 75);
      --fw-enf-convention-fg: oklch(65% 0.01 75);
      --fw-tint-teal-bg: oklch(26% 0.04 185);
      --fw-tint-teal-fg: oklch(82% 0.07 185);
      --fw-tint-teal-edge: oklch(45% 0.08 185);
      --fw-tint-violet-bg: oklch(27% 0.045 300);
      --fw-tint-violet-fg: oklch(83% 0.07 300);
      --fw-tint-violet-edge: oklch(48% 0.09 300);
      --fw-tint-amber-bg: oklch(28% 0.05 75);
      --fw-tint-amber-fg: oklch(85% 0.08 75);
      --fw-tint-amber-edge: oklch(55% 0.1 70);
      --fw-tint-blue-bg: oklch(26% 0.035 245);
      --fw-tint-blue-fg: oklch(82% 0.06 245);
      --fw-tint-blue-edge: oklch(46% 0.07 245);
      --fw-tint-rose-bg: oklch(26% 0.035 15);
      --fw-tint-rose-fg: oklch(84% 0.07 15);
      --fw-tint-rose-edge: oklch(48% 0.08 15);
      --fw-tint-slate-bg: oklch(25% 0.008 75);
      --fw-tint-slate-fg: oklch(80% 0.008 75);
      --fw-tint-slate-edge: oklch(38% 0.012 75);
      --fw-clause-given-ink: oklch(70% 0.01 75);
      --fw-clause-when-ink: oklch(84% 0.11 70);
      --fw-clause-then-ink: oklch(82% 0.09 185);
      --fw-level-interface-bg: oklch(28% 0.055 155);
      --fw-level-interface-fg: oklch(84% 0.08 155);
      --fw-behavior-bg: oklch(26% 0.035 245);
    }
    .richmd-badge--lens-modeling {
      background: var(--fw-lens-modeling-bg);
      color: var(--fw-lens-modeling-fg);
    }
    .richmd-badge--lens-depth {
      background: var(--fw-lens-depth-bg);
      color: var(--fw-lens-depth-fg);
    }
    .richmd-badge--lens-composition {
      background: var(--fw-lens-composition-bg);
      color: var(--fw-lens-composition-fg);
    }
    .richmd-badge--lens-state {
      background: var(--fw-lens-state-bg);
      color: var(--fw-lens-state-fg);
    }
    .richmd-badge--lens-invariants {
      background: var(--fw-lens-invariants-bg);
      color: var(--fw-lens-invariants-fg);
    }
    .richmd-badge--lens-robustness {
      background: var(--fw-lens-robustness-bg);
      color: var(--fw-lens-robustness-fg);
    }
    .richmd-badge--enf-mechanism {
      background: var(--fw-enf-mechanism-bg);
      color: var(--fw-enf-mechanism-fg);
    }
    .richmd-badge--enf-partial {
      background: var(--fw-enf-partial-bg);
      color: var(--fw-enf-partial-fg);
    }
    .richmd-badge--enf-convention {
      background: var(--fw-enf-convention-bg);
      color: var(--fw-enf-convention-fg);
    }
    .richmd-statement {
      border-top: none;
      border-left: 3px solid var(--fw-tint-slate-edge);
      padding: var(--richmd-space-3) var(--richmd-space-4);
      border-radius: var(--richmd-radius-md);
      margin: var(--richmd-space-2) 0;
    }
    .richmd-statement:first-of-type {
      border-top: none;
    }
    .richmd-statement--goal {
      border-left-color: var(--fw-tint-teal-edge);
    }
    .richmd-statement--no-goal {
      border-left-color: var(--fw-tint-rose-edge);
    }
    .richmd-statement--invariant {
      border-left-color: var(--fw-tint-amber-edge);
    }
    .richmd-statement--principle {
      border-left-color: var(--fw-tint-violet-edge);
    }
    .richmd-statement--behavior {
      border-left-color: var(--fw-tint-blue-edge);
    }
    .richmd-statement--behavior {
      display: block;
      background: var(--fw-behavior-bg);
    }
    .richmd-statement--behavior > .richmd-statement-label {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 0 var(--richmd-space-3);
      margin-bottom: var(--richmd-space-3);
    }
    .richmd-clause {
      display: grid;
      grid-template-columns: 4.5rem minmax(0, 1fr);
      gap: 0 var(--richmd-space-3);
      margin: var(--richmd-space-2) 0;
      align-items: baseline;
    }
    .richmd-clause + .richmd-clause {
      margin-top: var(--richmd-space-2);
    }
    .richmd-clause > .richmd-clause-keyword {
      text-align: right;
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      color: var(--fw-tint-slate-fg);
    }
    .richmd-clause > :not(.richmd-clause-keyword) {
      margin: 0;
      padding-left: var(--richmd-space-3);
      border-left: 1px solid var(--fw-tint-slate-edge);
    }
    .richmd-clause--given > .richmd-clause-keyword {
      color: var(--fw-clause-given-ink, var(--fw-tint-slate-fg));
    }
    .richmd-clause--given > :not(.richmd-clause-keyword) {
      border-left-color: var(--fw-tint-slate-edge);
    }
    .richmd-clause--when > .richmd-clause-keyword {
      color: var(--fw-clause-when-ink, var(--fw-tint-amber-fg));
    }
    .richmd-clause--when > :not(.richmd-clause-keyword) {
      border-left-color: var(--fw-tint-amber-edge);
    }
    .richmd-clause--then > .richmd-clause-keyword {
      color: var(--fw-clause-then-ink, var(--fw-tint-teal-fg));
    }
    .richmd-clause--then > :not(.richmd-clause-keyword) {
      border-left-color: var(--fw-tint-teal-edge);
    }
    .richmd-badge--pending-build {
      background: var(--fw-tint-blue-bg);
      color: var(--fw-tint-blue-fg);
    }
    .richmd-pending--build {
      border-color: var(--fw-tint-blue-edge);
    }
    .richmd-badge--pending-verify {
      background: var(--fw-tint-teal-bg);
      color: var(--fw-tint-teal-fg);
    }
    .richmd-pending--verify {
      border-color: var(--fw-tint-teal-edge);
    }
    .richmd-badge--pending-foundation {
      background: var(--fw-tint-violet-bg);
      color: var(--fw-tint-violet-fg);
    }
    .richmd-pending--foundation {
      border-color: var(--fw-tint-violet-edge);
    }
    .richmd-badge--pending-ruling {
      background: var(--fw-tint-amber-bg);
      color: var(--fw-tint-amber-fg);
    }
    .richmd-pending--ruling {
      border-color: var(--fw-tint-amber-edge);
    }
    .richmd-badge--level-interface {
      background: var(--fw-level-interface-bg);
      color: var(--fw-level-interface-fg);
    }
    .richmd-badge--level-boundary {
      background: var(--fw-tint-violet-bg);
      color: var(--fw-tint-violet-fg);
    }
    .richmd-card-grid--teal > .richmd-card {
      border: 1px solid var(--fw-tint-teal-edge);
      border-left: 3px solid var(--fw-tint-teal-edge);
      background: var(--fw-tint-teal-bg);
    }
    .richmd-card-grid--teal > .richmd-card .richmd-card-title {
      color: var(--fw-tint-teal-fg);
    }
    .richmd-card-grid--violet > .richmd-card {
      border: 1px solid var(--fw-tint-violet-edge);
      border-left: 3px solid var(--fw-tint-violet-edge);
      background: var(--fw-tint-violet-bg);
    }
    .richmd-card-grid--violet > .richmd-card .richmd-card-title {
      color: var(--fw-tint-violet-fg);
    }
    .richmd-card-grid--amber > .richmd-card {
      border: 1px solid var(--fw-tint-amber-edge);
      border-left: 3px solid var(--fw-tint-amber-edge);
      background: var(--fw-tint-amber-bg);
    }
    .richmd-card-grid--amber > .richmd-card .richmd-card-title {
      color: var(--fw-tint-amber-fg);
    }
    .richmd-card-grid--blue > .richmd-card {
      border: 1px solid var(--fw-tint-blue-edge);
      border-left: 3px solid var(--fw-tint-blue-edge);
      background: var(--fw-tint-blue-bg);
    }
    .richmd-card-grid--blue > .richmd-card .richmd-card-title {
      color: var(--fw-tint-blue-fg);
    }
    .richmd-card-grid--rose > .richmd-card {
      border: 1px solid var(--fw-tint-rose-edge);
      border-left: 3px solid var(--fw-tint-rose-edge);
      background: var(--fw-tint-rose-bg);
    }
    .richmd-card-grid--rose > .richmd-card .richmd-card-title {
      color: var(--fw-tint-rose-fg);
    }
    .richmd-card-grid--slate > .richmd-card {
      border: 1px solid var(--fw-tint-slate-edge);
      border-left: 3px solid var(--fw-tint-slate-edge);
      background: var(--fw-tint-slate-bg);
    }
    .richmd-card-grid--slate > .richmd-card .richmd-card-title {
      color: var(--fw-tint-slate-fg);
    }
    .richmd-group {
      margin: var(--richmd-space-5) 0;
      padding-left: var(--richmd-space-4);
      border-left: 3px solid var(--fw-tint-slate-edge);
    }
    .richmd-group > h3 {
      margin: 0 0 var(--richmd-space-3);
      font-size: var(--richmd-text-sm);
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--fw-tint-slate-fg);
    }
    .richmd-group--goal {
      border-left-color: var(--fw-tint-teal-edge);
    }
    .richmd-group--goal > h3 {
      color: var(--fw-tint-teal-fg);
    }
    .richmd-group--no-goal {
      border-left-color: var(--fw-tint-rose-edge);
    }
    .richmd-group--no-goal > h3 {
      color: var(--fw-tint-rose-fg);
    }
    .richmd-group--invariant {
      border-left-color: var(--fw-tint-amber-edge);
    }
    .richmd-group--invariant > h3 {
      color: var(--fw-tint-amber-fg);
    }
    .richmd-group--principle {
      border-left-color: var(--fw-tint-violet-edge);
    }
    .richmd-group--principle > h3 {
      color: var(--fw-tint-violet-fg);
    }
    .richmd-group .richmd-card-grid {
      margin: 0;
    }
    .richmd-card--goal {
      border-left: 3px solid var(--fw-tint-teal-edge);
    }
    .richmd-card--no-goal {
      border-left: 3px solid var(--fw-tint-rose-edge);
    }
    .richmd-card--invariant {
      border-left: 3px solid var(--fw-tint-amber-edge);
    }
    .richmd-card--principle {
      border-left: 3px solid var(--fw-tint-violet-edge);
    }
    .richmd-group-legend {
      margin: var(--richmd-space-4) 0;
      font-size: var(--richmd-text-sm);
    }
    .richmd-group-legend > summary {
      cursor: pointer;
      font-weight: 600;
      color: var(--fw-tint-slate-fg);
    }
    .richmd-group-legend-body {
      display: grid;
      grid-template-columns: max-content 1fr;
      gap: var(--richmd-space-2) var(--richmd-space-4);
      margin-top: var(--richmd-space-3);
    }
    .richmd-group-legend-term {
      font-weight: 600;
      color: var(--fw-tint-slate-fg);
    }
    .richmd-group-legend-row {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: var(--richmd-space-2);
    }
    .richmd-group-legend-note {
      color: var(--fw-tint-slate-fg);
    }
    .richmd-group-legend--goal {
      background: var(--fw-tint-teal-bg);
      color: var(--fw-tint-teal-fg);
    }
    .richmd-group-legend--no-goal {
      background: var(--fw-tint-rose-bg);
      color: var(--fw-tint-rose-fg);
    }
    .richmd-group-legend--invariant {
      background: var(--fw-tint-amber-bg);
      color: var(--fw-tint-amber-fg);
    }
    .richmd-group-legend--principle {
      background: var(--fw-tint-violet-bg);
      color: var(--fw-tint-violet-fg);
    }


    /* --- palette: warm paper ground + slate-teal voice.
       This <style> is unlayered, so with richmd's @layer richmd-base (upstream)
       a plain .richmd-doc override wins over the base theme regardless of the
       base's own selector specificity — no need to match its
       [data-richmd-theme="light"] selector list. --- */
    .richmd-doc {
      --richmd-color-bg: #fbfaf8;
      --richmd-color-bg-alt: #f3f1ec;
      --richmd-color-surface: #ffffff;
      --richmd-color-surface-2: #f3f1ec;
      --richmd-color-border: rgba(20,24,31,0.10);
      --richmd-color-border-strong: rgba(20,24,31,0.20);
      --richmd-color-text: #14181f;
      --richmd-color-text-muted: #55606d;
      --richmd-color-text-faint: #8a929d;
      --richmd-color-link: #2d6a6a;
      --richmd-color-link-hover: #1f4d4d;
      /* central column: match mockup 1000px (richmd wide is 1080, base is 760) */
      --richmd-content-width: 1000px;
      --richmd-content-width-wide: 1000px;
      --richmd-color-accent-tint: #e4efec;
      --richmd-color-accent-solid: #2d6a6a;
      --richmd-color-accent-solid-hover: #1f4d4d;
      --richmd-color-accent-text: #1f4d4d;
      /* accent2 = the violet tint-fg, so chart category 2 reads violet (mockup) */
      --richmd-color-accent2-solid: #6a4a86;
      --richmd-color-accent2-text: #52386a;
      /* categorical ramp for charts — the six tint families as concrete hex,
         matching the mockup order: teal, violet, amber, blue, rose, slate.
         cat-1/cat-2 alias accent-solid/accent2-solid (teal, violet); cat-3..6
         continue amber, blue, rose, slate. */
      --richmd-color-cat-3: #8a5a12;
      --richmd-color-cat-4: #3a5a86;
      --richmd-color-cat-5: #9a3f5f;
      --richmd-color-cat-6: #5a6152;
      /* type: Fraunces display (hero + numerals), Inter body, JetBrains mono */
      --richmd-font-heading: "Fraunces", Georgia, "Times New Roman", serif;
      --richmd-font-heading-weight: 500;
      --richmd-font-body: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
      --richmd-font-mono: "JetBrains Mono", ui-monospace, Menlo, Consolas, monospace;
      /* base text size: mockup is 15px, richmd default is 16px. Cascades into
         cards, toc, blockquote, pre, table body. */
      --richmd-text-base: 15px;
      /* callout semantic ramps -> the warm tint palette (richmd default is a
         cold indigo/blue). info=blue tint, warning=amber, danger=rose. */
      --richmd-color-info-tint: var(--fw-tint-blue-bg);   --richmd-color-info-border: var(--fw-tint-blue-edge);   --richmd-color-info-text: var(--fw-tint-blue-fg);   --richmd-color-info-solid: var(--fw-tint-blue-fg);
      --richmd-color-warning-tint: var(--fw-tint-amber-bg); --richmd-color-warning-border: var(--fw-tint-amber-edge); --richmd-color-warning-text: var(--fw-tint-amber-fg); --richmd-color-warning-solid: var(--fw-tint-amber-fg);
      --richmd-color-danger-tint: var(--fw-tint-rose-bg);  --richmd-color-danger-border: var(--fw-tint-rose-edge);  --richmd-color-danger-text: var(--fw-tint-rose-fg);  --richmd-color-danger-solid: var(--fw-tint-rose-fg);
    }
    /* --- dark palette: one attribute-keyed block. richmd (upstream) always
       mirrors the RESOLVED theme onto .richmd-doc[data-richmd-theme], OS-driven
       or explicit, so this single selector covers both — no media query and no
       forced-dark duplicate needed. --- */
    .richmd-doc[data-richmd-theme="dark"] {
      --richmd-color-bg: #0f1216;
      --richmd-color-bg-alt: #171b21;
      --richmd-color-surface: #141920;
      --richmd-color-surface-2: #171b21;
      --richmd-color-border: rgba(233,235,239,0.10);
      --richmd-color-border-strong: rgba(233,235,239,0.20);
      --richmd-color-text: #e9ebef;
      --richmd-color-text-muted: #a6adb8;
      --richmd-color-text-faint: #727b86;
      --richmd-color-link: #7bc4c0;
      --richmd-color-link-hover: #a3d8d5;
      --richmd-color-accent-tint: rgba(123,196,192,0.14);
      --richmd-color-accent-solid: #7bc4c0;
      --richmd-color-accent-text: #a3d8d5;
    }
    /* ===================================================================
       COMPONENT BEATS — restyle richmd's own DOM to the mockup, beat for
       beat. richmd already emits the structure (.richmd-topbar, .richmd-group,
       .richmd-statement, .richmd-card-grid, .richmd-callout, .richmd-stat-grid,
       .richmd-diagram); this section only re-skins it.
       =================================================================== */

    /* --- sticky top bar: brand + pill theme toggle --- */
    .richmd-topbar {
      position: sticky; top: 0; z-index: 20;
      background: color-mix(in srgb, var(--richmd-color-bg) 88%, transparent);
      backdrop-filter: blur(8px);
      border-bottom: 1px solid var(--richmd-color-border);
      padding: var(--richmd-space-4) var(--richmd-space-5);
    }
    .richmd-brand {
      font-family: var(--richmd-font-heading); font-weight: 600; font-size: 18px;
      letter-spacing: -0.01em; color: var(--richmd-color-text);
    }
    .richmd-theme-toggle {
      border: 1px solid var(--richmd-color-border-strong);
      background: var(--richmd-color-surface); color: var(--richmd-color-text-muted);
      border-radius: 999px; padding: 5px 13px; font-size: 12px; font-weight: 600;
    }

    /* --- HERO: two-column grid (thesis left, fixpoint mark right). The
       masthead hook wraps eyebrow+H1+lede in .richmd-hero-copy and the mark in
       .richmd-fixpoint, both inside .richmd-hero-grid. --- */
    .richmd-hero-grid {
      display: grid; grid-template-columns: 1fr 200px;
      gap: var(--richmd-space-7); align-items: center;
      padding: var(--richmd-space-8) 0 var(--richmd-space-7);
      border-bottom: 1px solid var(--richmd-color-border);
      margin-bottom: var(--richmd-space-7);
    }
    .richmd-eyebrow {
      font-size: 12px; font-weight: 600; letter-spacing: 0.12em;
      text-transform: uppercase; color: var(--richmd-color-accent-text);
      margin-bottom: var(--richmd-space-4);
    }
    .richmd-hero-grid h1 {
      font-family: var(--richmd-font-heading); font-weight: 500; font-size: 44px;
      line-height: 1.05; letter-spacing: -0.02em; font-variation-settings: "opsz" 144;
      margin: 0 0 var(--richmd-space-4);
    }
    .richmd-hero-grid .richmd-lede {
      font-size: 19px; color: var(--richmd-color-text-muted); max-width: 46ch; margin: 0;
    }
    .richmd-hero-grid .richmd-lede strong { color: var(--richmd-color-text); }
    .richmd-fixpoint { max-width: 200px; margin: 0; }

    /* --- SECTION HEADINGS: serif display title. The design docs carry their
       own LITERAL section numbers (00 Foundation, 01 …) — a meaningful,
       00-based scheme referenced across the layer (e.g. CONTEXT §04.1), so the
       overlay does NOT auto-number (no counter): it only sets the serif face,
       size, and a top rule. The leading number reads as part of the serif
       heading. --- */
    .richmd-container h1 { font-variation-settings: "opsz" 144; letter-spacing: -0.02em; }
    .richmd-container h2 {
      font-size: 26px; /* match mockup .sec-title (richmd base is 39px) */
      font-variation-settings: "opsz" 60; letter-spacing: -0.015em;
      border-top: 1px solid var(--richmd-color-border);
      padding-top: var(--richmd-space-6); margin-top: var(--richmd-space-8);
    }
    .richmd-lede { font-size: var(--richmd-text-lg); }

    /* --- FOUNDATION GROUPS: left-rule + uppercase group label + tinted cards.
       richmd emits .richmd-group--goal > h3 + .richmd-card-grid already. --- */
    .richmd-group { padding-left: var(--richmd-space-5); border-left: 2px solid var(--richmd-color-border-strong); margin: var(--richmd-space-6) 0; }
    .richmd-group > h3 {
      font-family: var(--richmd-font-body); font-size: 12px; font-weight: 700;
      letter-spacing: 0.1em; text-transform: uppercase; margin: 0 0 var(--richmd-space-4);
    }
    .richmd-group--goal      { border-left-color: var(--fw-tint-teal-edge);   } .richmd-group--goal > h3      { color: var(--fw-tint-teal-fg); }
    .richmd-group--no-goal   { border-left-color: var(--fw-tint-rose-edge);   } .richmd-group--no-goal > h3   { color: var(--fw-tint-rose-fg); }
    .richmd-group--invariant { border-left-color: var(--fw-tint-amber-edge);  } .richmd-group--invariant > h3 { color: var(--fw-tint-amber-fg); }
    .richmd-group--principle { border-left-color: var(--fw-tint-violet-edge); } .richmd-group--principle > h3 { color: var(--fw-tint-violet-fg); }
    /* foundation cards STACK one-per-row (mockup), not a 3-col grid — richmd's
       card-grid defaults to repeat(3,1fr); force a single column. */
    .richmd-group .richmd-card-grid { grid-template-columns: 1fr; }

    /* card proportions + tint per foundation kind (richmd emits .richmd-card--goal etc.) */
    .richmd-card { border-radius: 12px; padding: var(--richmd-space-4); box-shadow: 0 1px 2px rgba(20,24,31,0.04); gap: var(--richmd-space-2); }
    /* card title: mockup is Inter 15/700, NOT richmd's Fraunces 19/500 */
    .richmd-card-title, .richmd-card-title strong {
      font-family: var(--richmd-font-body); font-weight: 700; font-size: 15px; line-height: 1.25;
    }
    /* card body: mockup 13px */
    .richmd-card-body, .richmd-card-body p { font-size: 13px; line-height: 1.55; }
    .richmd-card--goal      { background: var(--fw-tint-teal-bg);   border-left: 3px solid var(--fw-tint-teal-edge);   } .richmd-card--goal .richmd-card-title { color: var(--fw-tint-teal-fg); }
    .richmd-card--no-goal   { background: var(--fw-tint-rose-bg);   border-left: 3px solid var(--fw-tint-rose-edge);   } .richmd-card--no-goal .richmd-card-title { color: var(--fw-tint-rose-fg); }
    .richmd-card--invariant { background: var(--fw-tint-amber-bg);  border-left: 3px solid var(--fw-tint-amber-edge);  } .richmd-card--invariant .richmd-card-title { color: var(--fw-tint-amber-fg); }
    .richmd-card--principle { background: var(--fw-tint-violet-bg); border-left: 3px solid var(--fw-tint-violet-edge); } .richmd-card--principle .richmd-card-title { color: var(--fw-tint-violet-fg); }

    /* --- callouts, diagrams, tables, details, stat tiles: mockup radii + tighter type --- */
    .richmd-diagram, .richmd-callout, .richmd-toc, .richmd-details, .richmd-table-wrap { border-radius: 12px; }

    /* --- WIDGET DETAIL PARITY (measured field-by-field against the mockup) --- */
    /* stat tile: 12px radius (richmd base 10), label 11px. richmd's stat-tile
       now emits richmd-stat-delta--up / --down from the dir= attr (richmd
       60bffba), so tint the delta BY DIRECTION: up=teal, down=danger/rose —
       the workaround of one flat color is gone. */
    .richmd-stat { border-radius: 12px; }
    .richmd-stat-label { font-size: 11px; }
    .richmd-stat-delta--up   { color: var(--fw-tint-teal-fg); }
    .richmd-stat-delta--down { color: var(--fw-tint-rose-fg); }
    /* callout: richmd sets .richmd-callout-body color to ink, overriding the
       root's tint. Re-tint body text per callout kind so title+body read in
       the tint (mockup behavior). */
    .richmd-callout--info .richmd-callout-body    { color: var(--fw-tint-blue-fg); }
    .richmd-callout--warning .richmd-callout-body { color: var(--fw-tint-amber-fg); }
    .richmd-callout--danger .richmd-callout-body  { color: var(--fw-tint-rose-fg); }
    .richmd-callout .richmd-callout-body strong { color: inherit; }
    /* TITLE ABOVE, BODY BELOW (mockup). Two authoring shapes both land here:
       (a) `.callout` written as two paragraphs — the FIRST body <p> is the
           title (bold, block); following <p> is the body.
       (b) `:::info` emits a .richmd-callout-title element — block, above. */
    .richmd-callout-body > p:first-child > strong:only-child,
    .richmd-callout-body > p:first-child:has(> strong:only-child) {
      display: block; font-weight: 700; margin: 0 0 var(--richmd-space-1);
    }
    .richmd-callout-title {
      display: block; font-weight: 700; margin: 0 0 var(--richmd-space-1);
    }
    .richmd-callout-body > p { margin: 0; }
    .richmd-callout-body > p + p { margin-top: var(--richmd-space-1); }
    /* lens pill: mockup is 10px / 700 / UPPERCASE / tight pad (richmd base badge is 12/600/none) */
    .richmd-badge[class*="--lens-"] {
      font-size: 10px; font-weight: 700; text-transform: uppercase;
      letter-spacing: 0.04em; padding: 1px 8px;
    }
    /* hide the principle id chip (P1/P2/…): it is the FIRST badge in a
       principle's card-meta (the lens pill follows it). Targeting :first-child
       keeps lens pills and invariant enforcement chips untouched. */
    .richmd-card--principle .richmd-card-meta > .richmd-badge:first-child {
      display: none;
    }
    /* table header + body: mockup 11px / 13.5px (richmd base 12 / text-base) */
    .richmd-doc th { font-size: 11px; }
    .richmd-doc td { font-size: 13.5px; }
    /* inline code: mockup is 12px muted weight 400. richmd base uses 0.87em
       which inflates when an ancestor bumps the em (observed 15-16px); pin an
       ABSOLUTE 12px so it's stable regardless of parent size. */
    .richmd-doc code { font-weight: 400; font-size: 12px; color: var(--richmd-color-text-faint); }
    /* code inside a code block stays full size / ink (it's not inline chrome) */
    .richmd-doc pre code { font-size: 13px; color: var(--richmd-color-text); }
    /* SVG figure (:::embedded-svg) — richmd emits
       <figure><div.richmd-embedded-svg><svg/></div><figcaption/></figure>.
       Frame the FIGURE (so the caption is inside the card too), center the svg,
       mute the caption. Matches the mockup .figure. */
    figure:has(> .richmd-embedded-svg) {
      text-align: center; margin: var(--richmd-space-4) 0;
      background: var(--richmd-color-surface);
      border: 1px solid var(--richmd-color-border);
      border-radius: 12px; padding: var(--richmd-space-5);
    }
    .richmd-embedded-svg svg { max-width: 200px; display: inline-block; }
    figure:has(> .richmd-embedded-svg) figcaption {
      font-size: 12px; color: var(--richmd-color-text-faint); margin-top: var(--richmd-space-3);
    }
    /* details/disclosure body: richmd leaves the body flush with no inset.
       Inset it to match the mockup .disc-body (padding around the content). */
    .richmd-details > summary { padding: var(--richmd-space-3) var(--richmd-space-4); }
    .richmd-details > *:not(summary) {
      margin: 0; padding: 0 var(--richmd-space-4) var(--richmd-space-4);
      font-size: 13.5px; color: var(--richmd-color-text-muted);
    }
    /* --- CALLOUT ICON: richmd's theme styles .richmd-callout-icon but callout.lua
       never emits one (styled-but-empty slot). Inject a per-tint SVG icon as a
       ::before so it matches the mockup: info=circle-i, warning=triangle-!,
       danger=circle-x. Colored via the callout's own currentColor. --- */
    .richmd-callout { align-items: flex-start; }
    .richmd-callout::before {
      content: ""; flex: none; width: 18px; height: 18px; margin-top: 2px;
      background: currentColor; -webkit-mask-repeat: no-repeat; mask-repeat: no-repeat;
      -webkit-mask-position: center; mask-position: center;
      -webkit-mask-size: contain; mask-size: contain;
    }
    .richmd-callout--info::before {
      -webkit-mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><circle cx="10" cy="10" r="9" fill="none" stroke="black" stroke-width="1.6"/><rect x="9" y="8.5" width="2" height="6" rx="1"/><circle cx="10" cy="5.5" r="1.2"/></svg>');
      mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><circle cx="10" cy="10" r="9" fill="none" stroke="black" stroke-width="1.6"/><rect x="9" y="8.5" width="2" height="6" rx="1"/><circle cx="10" cy="5.5" r="1.2"/></svg>');
    }
    .richmd-callout--warning::before {
      -webkit-mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 2 L19 18 H1 Z" fill="none" stroke="black" stroke-width="1.6" stroke-linejoin="round"/><rect x="9" y="8" width="2" height="5" rx="1"/><circle cx="10" cy="15" r="1.1"/></svg>');
      mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 2 L19 18 H1 Z" fill="none" stroke="black" stroke-width="1.6" stroke-linejoin="round"/><rect x="9" y="8" width="2" height="5" rx="1"/><circle cx="10" cy="15" r="1.1"/></svg>');
    }
    .richmd-callout--danger::before {
      -webkit-mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><circle cx="10" cy="10" r="9" fill="none" stroke="black" stroke-width="1.6"/><path d="M6.5 6.5 L13.5 13.5 M13.5 6.5 L6.5 13.5" stroke="black" stroke-width="1.6"/></svg>');
      mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><circle cx="10" cy="10" r="9" fill="none" stroke="black" stroke-width="1.6"/><path d="M6.5 6.5 L13.5 13.5 M13.5 6.5 L6.5 13.5" stroke="black" stroke-width="1.6"/></svg>');
    }
    /* stat value: mockup 34px (richmd base is 39px / --richmd-text-3xl) */
    .richmd-stat-value { font-family: var(--richmd-font-heading); font-weight: 500; font-size: 34px; font-variation-settings: "opsz" 40; }
    .richmd-diagram-title { font-size: 11px; letter-spacing: 0.08em; }
    /* section lede/intro prose under each h2: mockup is 14px muted, not 16px ink */
    .richmd-container h2 + p { font-size: 14px; color: var(--richmd-color-text-muted); margin-top: var(--richmd-space-2); }
    /* the doc-level intro paragraph (after the H1 hero): keep as lede size, muted */
    .richmd-container > p { color: var(--richmd-color-text-muted); }

    /* --- PENDING-LEDGER: the TYPED-STATEMENT vertical pattern (title → break →
       meta [pill + since on one line] → break → description). Dashed tinted
       card. Mirrors goal/invariant/principle rhythm. --- */
    .richmd-pending {
      border: 1px dashed var(--richmd-color-border-strong); border-radius: 12px;
      padding: var(--richmd-space-4) var(--richmd-space-5);
      background: var(--richmd-color-bg-alt);
      margin: var(--richmd-space-3) 0;
    }
    .richmd-pending-title {
      font-family: var(--richmd-font-body); font-weight: 700; font-size: 15px;
      line-height: 1.25; margin: 0 0 var(--richmd-space-2);
    }
    /* meta row: kind pill + since date on ONE line */
    .richmd-pending-meta {
      display: flex; align-items: center; gap: var(--richmd-space-3);
      margin: 0 0 var(--richmd-space-2);
    }
    .richmd-pending-meta:last-child { margin-bottom: 0; }
    .richmd-pending-meta > .richmd-badge {
      border-radius: 999px; text-transform: none; letter-spacing: normal;
      font-family: var(--richmd-font-mono); font-size: 11px; font-weight: 600; padding: 2px 9px;
    }
    .richmd-pending-body { font-size: 13.5px; color: var(--richmd-color-text-muted); }
    .richmd-pending-body > p { margin: 0; }
    /* the per-kind pending pill AND the per-kind entry edge are emitted from
       the schema's pending kinds — see the _PENDING_TINT loop in the overlay
       builder, so a new kind reprojects instead of needing a hand-edit here. */
    .richmd-pending-since {
      color: var(--richmd-color-text-faint);
      font-family: var(--richmd-font-mono); font-size: 11px; white-space: nowrap;
    }

    @media (max-width: 820px) {
      .richmd-hero-grid { grid-template-columns: 1fr; }
      .richmd-hero-grid h1 { font-size: 40px; }
    }
  

]==] .. "</style>"
  )
end

-- fonts_block() -> a <link> loading Fraunces (variable, opsz axis). richmd's
-- base @import does not load Fraunces, so the display face needs this.
local function fonts_block()
  return pandoc.RawBlock(
    "html",
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
      .. '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
      .. '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
      .. 'family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400&display=swap">'
  )
end

-- fixpoint_block() -> the signature hero mark as inline SVG (accent-themed).
local function fixpoint_block()
  return pandoc.RawBlock("html", [==[
<div class="richmd-fixpoint" aria-hidden="true">
  <svg viewBox="0 0 200 200" style="width:100%;height:auto;">
    <circle cx="100" cy="100" r="86" fill="none" stroke="var(--richmd-color-accent-solid)" stroke-width="1.5" opacity=".5"/>
    <rect x="58" y="46" width="84" height="26" rx="5" fill="var(--richmd-color-accent-tint)" stroke="var(--richmd-color-accent-solid)" stroke-width="1.2"/>
    <rect x="58" y="87" width="84" height="26" rx="5" fill="var(--richmd-color-accent-tint)" stroke="var(--richmd-color-accent-solid)" stroke-width="1.2"/>
    <rect x="58" y="128" width="84" height="26" rx="5" fill="var(--richmd-color-accent-tint)" stroke="var(--richmd-color-accent-solid)" stroke-width="1.2"/>
    <path d="M142 59 C182 70 182 141 142 141" fill="none" stroke="var(--richmd-color-accent-solid)" stroke-width="1.5"/>
    <path d="M58 100 C24 100 24 59 56 59" fill="none" stroke="var(--richmd-color-accent-solid)" stroke-width="1.5"/>
  </svg>
  <div style="font-family:var(--richmd-font-mono);font-size:11px;color:var(--richmd-color-text-faint);margin-top:8px;letter-spacing:.02em;">layer &#8635; layer</div>
</div>]==])
end

return {
  masthead = function(doc_meta)
    local out = {}
    table.insert(out, style_block())
    table.insert(out, fonts_block())
    table.insert(out, pandoc.RawBlock("html", '<div class="richmd-hero-grid"><div class="richmd-hero-copy">'))
    do
      local inlines = meta_to_inlines(doc_meta and doc_meta['eyebrow'])
      if inlines then
        table.insert(
          out,
          pandoc.Div(
            { pandoc.Plain(inlines) },
            pandoc.Attr("", { "richmd-eyebrow" })
          )
        )
      end
    end
    do
      local inlines = meta_to_inlines(doc_meta and doc_meta['hero_title'])
      if inlines then
        table.insert(out, pandoc.Header(1, inlines))
      end
    end
    do
      local inlines = meta_to_inlines(doc_meta and doc_meta['lede'])
      if inlines then
        table.insert(out, pandoc.RawBlock("html", '<p class="richmd-lede">'))
        table.insert(out, pandoc.Plain(inlines))
        table.insert(out, pandoc.RawBlock("html", "</p>"))
      end
    end
    table.insert(out, pandoc.RawBlock("html", '</div>'))
    table.insert(out, fixpoint_block())
    table.insert(out, pandoc.RawBlock("html", '</div>'))
    if #out == 0 then return nil end
    return pandoc.Blocks(out)
  end,
  colophon = function(doc_meta)
    local out = {}
    do
      local inlines = meta_to_inlines(doc_meta and doc_meta['footer'])
      if inlines then
        table.insert(
          out,
          pandoc.Div(
            { pandoc.Plain(inlines) },
            pandoc.Attr("", { "richmd-colophon" })
          )
        )
      end
    end
    if #out == 0 then return nil end
    return pandoc.Blocks(out)
  end,
}
