-- Generated by scripts/richmd-project — do not hand-edit.
-- Group render hook (richmd#27 / ADR-0015 / ADR-0025): the 5th projected
-- contract. Claims the four foundation statement kinds and renders each
-- maximal consecutive run as ONE titled per-kind CARD SECTION — a
-- <section class="richmd-group richmd-group--<kind>"> whose <h3> is the
-- kind's plural label over a richmd-card-grid of NATIVE .richmd-card Divs.
-- The hook RESHAPES each already-rendered .richmd-statement into the native
-- card slots (ADR-0025 amended): label -> richmd-card-title, badge Spans ->
-- richmd-card-meta (omitted when none), body -> richmd-card-body, so a
-- foundation card reuses the SAME structure as every :::cards card. Each
-- card also carries richmd-card--<kind> for the per-kind accent. The
-- per-block statement renderers are untouched — the reshape lives only here
-- (ADR-0025). The FIRST run rendered also prepends a collapsed "How to read
-- this" legend; a module-level latch keeps it to exactly one. Kind set +
-- legend vocabulary are schema-derived (foundation kinds, enforcement, lens).

-- LABELS: the plural section heading per foundation kind, built from the
-- schema kind strings (a schema kind change reprojects this map).
local LABELS = { ["goal"] = "Goals", ["no-goal"] = "No-goals", ["invariant"] = "Invariants", ["principle"] = "Principles" }

-- legend_emitted — module-level latch. The hook's render runs once per
-- consecutive run (four times over the foundation); the legend must appear
-- exactly once, so the FIRST run to render emits it and flips this latch.
local legend_emitted = false

-- legend() -> the collapsed "How to read this" <details> block, naming the
-- four foundation kinds and the enforcement + lens glyph key. Every
-- enumerated row is schema-derived (see the projector). Built as pandoc
-- nodes (a definition list inside a <details>/<summary>) so it renders
-- through richmd's own writer, no raw HTML string.
local function legend()
  local kind_dd = pandoc.Div(
    { pandoc.Plain({ pandoc.Span({ pandoc.Str("Goals") }, pandoc.Attr("", { "richmd-badge", "richmd-group-legend--goal" })), pandoc.Span({ pandoc.Str("No-goals") }, pandoc.Attr("", { "richmd-badge", "richmd-group-legend--no-goal" })), pandoc.Span({ pandoc.Str("Invariants") }, pandoc.Attr("", { "richmd-badge", "richmd-group-legend--invariant" })), pandoc.Span({ pandoc.Str("Principles") }, pandoc.Attr("", { "richmd-badge", "richmd-group-legend--principle" })) }) },
    pandoc.Attr("", { "richmd-group-legend-row" })
  )
  local lens_dd = pandoc.Div(
    { pandoc.Plain({ pandoc.Span({ pandoc.Str("modeling") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--lens-modeling" })), pandoc.Span({ pandoc.Str("depth") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--lens-depth" })), pandoc.Span({ pandoc.Str("composition") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--lens-composition" })), pandoc.Span({ pandoc.Str("state") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--lens-state" })), pandoc.Span({ pandoc.Str("invariants") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--lens-invariants" })), pandoc.Span({ pandoc.Str("robustness") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--lens-robustness" })), pandoc.Span({ pandoc.Str("judgment axes") }, pandoc.Attr("", { "richmd-group-legend-note" })) }) },
    pandoc.Attr("", { "richmd-group-legend-row" })
  )
  local enf_dd = pandoc.Div(
    { pandoc.Plain({ pandoc.Span({ pandoc.Str("mechanism") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--neutral", "richmd-badge--enf-mechanism" })), pandoc.Span({ pandoc.Str("partial") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--neutral", "richmd-badge--enf-partial" })), pandoc.Span({ pandoc.Str("convention") }, pandoc.Attr("", { "richmd-badge", "richmd-badge--neutral", "richmd-badge--enf-convention" })), pandoc.Span({ pandoc.Str("strong → weak") }, pandoc.Attr("", { "richmd-group-legend-note" })) }) },
    pandoc.Attr("", { "richmd-group-legend-row" })
  )
  local rows = {
    pandoc.Plain({ pandoc.Span({ pandoc.Str("Foundation") }, pandoc.Attr("", { "richmd-group-legend-term" })) }),
    kind_dd,
    pandoc.Plain({ pandoc.Span({ pandoc.Str("Lenses") }, pandoc.Attr("", { "richmd-group-legend-term" })) }),
    lens_dd,
    pandoc.Plain({ pandoc.Span({ pandoc.Str("Enforcement") }, pandoc.Attr("", { "richmd-group-legend-term" })) }),
    enf_dd,
  }
  local body = pandoc.Div(rows, pandoc.Attr("", { "richmd-group-legend-body" }))
  return pandoc.Div(
    {
      pandoc.RawBlock("html", "<details class=\"richmd-group-legend\"><summary>How to read this</summary>"),
      body,
      pandoc.RawBlock("html", "</details>"),
    },
    pandoc.Attr("", { "richmd-group-legend-wrap" })
  )
end

-- has_class(el, want) -> true if el's Attr classes include `want`.
local function has_class(el, want)
  if not el.attr then return false end
  for _, c in ipairs(el.attr.classes or {}) do
    if c == want then return true end
  end
  return false
end

-- reshape(stmt, kind) -> a native .richmd-card Div built from an
-- already-rendered .richmd-statement Div, so a foundation card reuses the
-- SAME slot anatomy every :::cards card has (ADR-0025 amended): the
-- statement's LABEL inlines become richmd-card-title, its badge Spans
-- become richmd-card-meta (omitted when there are none), and its body
-- becomes richmd-card-body as a BARE <p> (the statement's
-- <p class="richmd-statement-body"> marker RawBlocks are stripped, so the
-- card body is structurally identical to a real :::cards card body). The
-- badge Spans are carried INTACT so their
-- richmd-badge--lens-* / richmd-badge--enf-* modifier classes survive for
-- the overlay. The per-block statement renderer is untouched — the reshape
-- is confined to this group hook.
local function reshape(stmt, kind)
  -- locate the statement's child Divs by class; everything that is neither
  -- the label Div is body content (the statement body is a
  -- RawBlock/Plain/RawBlock trio, not a single Div, so collect the run).
  local label_inlines = {}
  local badge_spans = {}
  local body_blocks = {}
  for _, child in ipairs(stmt.content) do
    if child.tag == "Div" and has_class(child, "richmd-statement-label") then
      -- the label Div holds a single Plain of [Strong (the label), then
      -- zero or more richmd-badge Spans]. Split the label inlines from the
      -- badge Spans: a richmd-badge Span goes to meta, everything else
      -- (the Strong, any Space) stays as the title.
      local head = child.content[1]
      for _, inl in ipairs((head and head.content) or {}) do
        if inl.tag == "Span" and has_class(inl, "richmd-badge") then
          table.insert(badge_spans, inl)
        else
          table.insert(label_inlines, inl)
        end
      end
    elseif child.tag == "RawBlock"
      and (child.text == '<p class="richmd-statement-body">' or child.text == "</p>") then
      -- The per-block statement renderer brackets the body Para in raw
      -- <p class="richmd-statement-body"> ... </p> markers (a Para carries
      -- no Attr, so labeled-block.lua hangs the class on raw HTML). A real
      -- :::cards card body is a BARE <p> — cards.lua wraps the authored
      -- Para in .richmd-card-body with no statement class. Drop these two
      -- marker RawBlocks so the card body matches a real cards card exactly;
      -- the Plain between them is promoted to a Para just below.
    elseif child.tag == "Plain" then
      -- the statement body's flattened Plain (between the dropped markers).
      -- Promote to a Para so it renders as a clean <p>...</p> — the same
      -- shape cards.lua's authored-markdown card body produces.
      table.insert(body_blocks, pandoc.Para(child.content))
    else
      table.insert(body_blocks, child)
    end
  end
  local card_children = {}
  table.insert(
    card_children,
    pandoc.Div(
      { pandoc.Plain(label_inlines) },
      pandoc.Attr("", { "richmd-card-title" })
    )
  )
  -- meta only when the statement carried badges (goals/no-goals have none).
  if #badge_spans > 0 then
    table.insert(
      card_children,
      pandoc.Div(
        { pandoc.Plain(badge_spans) },
        pandoc.Attr("", { "richmd-card-meta" })
      )
    )
  end
  -- body: the statement's body blocks wrapped in richmd-card-body, exactly
  -- as cards.lua wraps a card body (a no-goal may have no body — then the
  -- run is empty and the wrapper is simply empty, never a crash).
  table.insert(
    card_children,
    pandoc.Div(body_blocks, pandoc.Attr("", { "richmd-card-body" }))
  )
  return pandoc.Div(
    card_children,
    pandoc.Attr("", { "richmd-card", "richmd-card--" .. kind })
  )
end

return {
  kinds = { "goal", "no-goal", "invariant", "principle" },
  render = function(kind, rendered_blocks)
    -- RESHAPE each already-rendered .richmd-statement Div into a native
    -- .richmd-card (title/meta/body slots), laid in a richmd-card-grid under
    -- the section's <h3> — the same card structure every :::cards grid uses.
    local cards = {}
    for _, node in ipairs(rendered_blocks) do
      table.insert(cards, reshape(node, kind))
    end
    local grid = pandoc.Div(cards, pandoc.Attr("", { "richmd-card-grid" }))
    local label = LABELS[kind] or kind
    local heading = pandoc.Header(3, pandoc.Str(label))
    local section = pandoc.Div(
      { heading, grid },
      pandoc.Attr("", { "richmd-group", "richmd-group--" .. kind })
    )
    -- the FIRST run rendered prepends the legend, once (latch).
    if not legend_emitted then
      legend_emitted = true
      return pandoc.Blocks({ legend(), section })
    end
    return pandoc.Blocks({ section })
  end,
}
