-- Generated by scripts/richmd-project — do not hand-edit.
-- Structural renderer paired with cards.schema.json (richmd requires a
-- render function beside every block schema). Emits the block's rendered
-- slot anatomy using richmd's own shipped theme classes (ADR-0021).
-- The statement title comes from the declared `title=` attr (validated,
-- deterministic) — NOT a bold-first-line convention — so there is no
-- label-extraction helper; the whole block body is the description.

-- badge_span(text) -> a .richmd-badge Span (richmd's shipped badge class).
-- extra is an optional modifier class string; it may name several classes
-- separated by spaces (e.g. "richmd-badge--neutral richmd-badge--enf-x"),
-- each added as its own class so the emitted class attribute is well-formed.
local function badge_span(text, extra)
  local classes = { "richmd-badge" }
  if extra and extra ~= "" then
    for cls in string.gmatch(extra, "%S+") do
      table.insert(classes, cls)
    end
  end
  return pandoc.Span({ pandoc.Str(text) }, pandoc.Attr("", classes))
end

-- lens_badge(member) -> a lens pill Span carrying the per-lens modifier
-- class richmd-badge--lens-<member> alongside the base .richmd-badge. The
-- framework's semantic-look overlay (ADR-0024) keys the per-lens palette on
-- that modifier — richmd's base theme leaves lens pills monochrome.
local function lens_badge(member)
  return badge_span(member, "richmd-badge--lens-" .. member)
end

-- lens_badges(resolved_attrs) -> list of lens-pill Spans. A `lens=` attr
-- may be a `+` combo; split on `+` and emit one badge per member, in the
-- order written. Each member carries its own richmd-badge--lens-<member>
-- modifier class.
local function lens_badges(resolved_attrs)
  local out = {}
  local raw = resolved_attrs.lens
  if raw and raw ~= "" then
    for part in string.gmatch(raw, "[^+]+") do
      table.insert(out, lens_badge(part))
    end
  end
  return out
end

-- statement(label_inlines, badges, body_blocks, kind) -> .richmd-statement
-- Div. The label div holds the re-wrapped <strong> label FOLLOWED by the
-- badge row; the body is wrapped in a real <p class="richmd-statement-body">
-- exactly as labeled-block.lua does (Para carries no Attr, so raw HTML
-- markers bracket a flattened Para). When there is no label, the head row
-- still renders when badges are present (pending has badges but no label).
-- `kind`, when given, adds the richmd-statement--<kind> modifier class the
-- semantic-look overlay (ADR-0024) keys the per-kind accent on — richmd's
-- base theme renders all four kinds identically.
local function statement(label_inlines, badges, body_blocks, kind)
  local inner = {}
  local head = {}
  if label_inlines then
    table.insert(head, pandoc.Strong(label_inlines))
  end
  for _, b in ipairs(badges) do table.insert(head, b) end
  if #head > 0 then
    table.insert(
      inner,
      pandoc.Div(
        { pandoc.Plain(head) },
        pandoc.Attr("", { "richmd-statement-label" })
      )
    )
  end
  local body_inlines = {}
  for i, b in ipairs(body_blocks) do
    if i > 1 then table.insert(body_inlines, pandoc.SoftBreak()) end
    for _, inline in ipairs(b.content or {}) do
      table.insert(body_inlines, inline)
    end
  end
  table.insert(inner, pandoc.RawBlock("html", '<p class="richmd-statement-body">'))
  table.insert(inner, pandoc.Plain(body_inlines))
  table.insert(inner, pandoc.RawBlock("html", "</p>"))
  local classes = { "richmd-statement" }
  if kind and kind ~= "" then
    table.insert(classes, "richmd-statement--" .. kind)
  end
  return pandoc.Div(inner, pandoc.Attr("", classes))
end

return {
  render = function(block, resolved_attrs)
    local grid_classes = { "richmd-card-grid" }
    if resolved_attrs.tint and resolved_attrs.tint ~= "" then
      table.insert(grid_classes, "richmd-card-grid--" .. resolved_attrs.tint)
    end
    local grid_attrs = {}
    if resolved_attrs.cols then
      grid_attrs = { { "data-cols", resolved_attrs.cols } }
    end
    local grid_attr = pandoc.Attr("", grid_classes, grid_attrs)
    -- lift a resolved lens token (Code, class richmd-token,
    -- vocabulary=lens) out of a heading's inlines; return the member and
    -- the remaining title inlines (the lens span removed).
    local function split_lens(inlines)
      local member = nil
      local kept = {}
      for _, inl in ipairs(inlines) do
        local is_lens = false
        if inl.tag == "Code" and inl.attr then
          for _, c in ipairs(inl.attr.classes or {}) do
            if c == "richmd-token" then
              for _, kv in ipairs(inl.attr.attributes or {}) do
                if kv[1] == "vocabulary" and kv[2] == "lens" then
                  is_lens = true
                  for _, kv2 in ipairs(inl.attr.attributes) do
                    if kv2[1] == "member" then member = kv2[2] end
                  end
                end
              end
            end
          end
        end
        if not is_lens then table.insert(kept, inl) end
      end
      -- trim leading/trailing Space left where the lens span was.
      while kept[1] and (kept[1].tag == "Space" or kept[1].tag == "SoftBreak") do
        table.remove(kept, 1)
      end
      while kept[#kept] and (kept[#kept].tag == "Space" or kept[#kept].tag == "SoftBreak") do
        table.remove(kept)
      end
      return member, kept
    end
    local cards = {}
    local current = nil
    for _, blk in ipairs(block.content) do
      if blk.t == "Header" and blk.level == 3 then
        current = { heading = blk, body = {} }
        table.insert(cards, current)
      elseif current then
        table.insert(current.body, blk)
      end
    end
    local card_divs = {}
    for _, card in ipairs(cards) do
      local lens_member, title_inlines = split_lens(card.heading.content)
      local title_div = pandoc.Div(
        { pandoc.Plain(title_inlines) },
        pandoc.Attr("", { "richmd-card-title" })
      )
      local body_div =
        pandoc.Div(card.body, pandoc.Attr("", { "richmd-card-body" }))
      local badge_text = card.heading.attributes.badge
      local badge_tint = card.heading.attributes["badge-tint"]
      local meta_text = card.heading.attributes.meta
      local meta_children = {}
      if lens_member and lens_member ~= "" then
        table.insert(meta_children, lens_badge(lens_member))
      end
      if badge_text and badge_text ~= "" then
        local extra = nil
        if badge_tint and badge_tint ~= "" then
          extra = "richmd-badge--" .. badge_tint
        end
        table.insert(meta_children, badge_span(badge_text, extra))
      end
      if meta_text and meta_text ~= "" then
        table.insert(meta_children, pandoc.Str(meta_text))
      end
      local card_children = { title_div }
      if #meta_children > 0 then
        table.insert(
          card_children,
          pandoc.Div(
            { pandoc.Plain(meta_children) },
            pandoc.Attr("", { "richmd-card-meta" })
          )
        )
      end
      table.insert(card_children, body_div)
      table.insert(
        card_divs,
        pandoc.Div(card_children, pandoc.Attr("", { "richmd-card" }))
      )
    end
    return pandoc.Div(card_divs, grid_attr)
  end,
}
