-- Generated by scripts/richmd-project — do not hand-edit.
-- Structural renderer paired with no-goal.schema.json (richmd requires a
-- render function beside every block schema). Emits the block's rendered
-- slot anatomy using richmd's own shipped theme classes (ADR-0021).
-- The statement title comes from the declared `title=` attr (validated,
-- deterministic) — NOT a bold-first-line convention — so there is no
-- label-extraction helper; the whole block body is the description.

-- badge_span(text) -> a .richmd-badge Span (richmd's shipped badge class).
-- extra is an optional modifier class string; it may name several classes
-- separated by spaces (e.g. "richmd-badge--neutral richmd-badge--enf-x"),
-- each added as its own class so the emitted class attribute is well-formed.
local function badge_span(text, extra)
  local classes = { "richmd-badge" }
  if extra and extra ~= "" then
    for cls in string.gmatch(extra, "%S+") do
      table.insert(classes, cls)
    end
  end
  return pandoc.Span({ pandoc.Str(text) }, pandoc.Attr("", classes))
end

-- lens_badge(member) -> a lens pill Span carrying the per-lens modifier
-- class richmd-badge--lens-<member> alongside the base .richmd-badge. The
-- framework's semantic-look overlay (ADR-0024) keys the per-lens palette on
-- that modifier — richmd's base theme leaves lens pills monochrome.
local function lens_badge(member)
  return badge_span(member, "richmd-badge--lens-" .. member)
end

-- lens_badges(resolved_attrs) -> list of lens-pill Spans. A `lens=` attr
-- may be a `+` combo; split on `+` and emit one badge per member, in the
-- order written. Each member carries its own richmd-badge--lens-<member>
-- modifier class.
local function lens_badges(resolved_attrs)
  local out = {}
  local raw = resolved_attrs.lens
  if raw and raw ~= "" then
    for part in string.gmatch(raw, "[^+]+") do
      table.insert(out, lens_badge(part))
    end
  end
  return out
end

-- statement(label_inlines, badges, body_blocks, kind) -> .richmd-statement
-- Div. The label div holds the re-wrapped <strong> label FOLLOWED by the
-- badge row; the body is wrapped in a real <p class="richmd-statement-body">
-- exactly as labeled-block.lua does (Para carries no Attr, so raw HTML
-- markers bracket a flattened Para). When there is no label, the head row
-- still renders when badges are present (pending has badges but no label).
-- `kind`, when given, adds the richmd-statement--<kind> modifier class the
-- semantic-look overlay (ADR-0024) keys the per-kind accent on — richmd's
-- base theme renders all four kinds identically.
local function statement(label_inlines, badges, body_blocks, kind)
  local inner = {}
  local head = {}
  if label_inlines then
    table.insert(head, pandoc.Strong(label_inlines))
  end
  for _, b in ipairs(badges) do table.insert(head, b) end
  if #head > 0 then
    table.insert(
      inner,
      pandoc.Div(
        { pandoc.Plain(head) },
        pandoc.Attr("", { "richmd-statement-label" })
      )
    )
  end
  local body_inlines = {}
  for i, b in ipairs(body_blocks) do
    if i > 1 then table.insert(body_inlines, pandoc.SoftBreak()) end
    for _, inline in ipairs(b.content or {}) do
      table.insert(body_inlines, inline)
    end
  end
  table.insert(inner, pandoc.RawBlock("html", '<p class="richmd-statement-body">'))
  table.insert(inner, pandoc.Plain(body_inlines))
  table.insert(inner, pandoc.RawBlock("html", "</p>"))
  local classes = { "richmd-statement" }
  if kind and kind ~= "" then
    table.insert(classes, "richmd-statement--" .. kind)
  end
  return pandoc.Div(inner, pandoc.Attr("", classes))
end

return {
  render = function(block, resolved_attrs)
    local title = resolved_attrs.title or ""
    local label_inlines = (title ~= "") and { pandoc.Str(title) } or nil
    local badges = lens_badges(resolved_attrs)
    return statement(label_inlines, badges, block.content, 'no-goal')
  end,
}
