-- Generated by scripts/richmd-project — do not hand-edit.
-- Structural renderer paired with warning.schema.json (richmd requires a
-- render function beside every block schema). Emits the block's rendered
-- slot anatomy using richmd's own shipped theme classes (ADR-0021).

return {
  render = function(block, resolved_attrs)
    local classes = { "richmd-callout", "richmd-callout--warning" }
    local callout_tints = { info = true, warning = true, danger = true }
    local tint = resolved_attrs.tint
    if tint and callout_tints[tint] then
      table.insert(classes, "richmd-callout--" .. tint)
    end
    local body_content = {}
    if resolved_attrs.title and resolved_attrs.title ~= "" then
      table.insert(
        body_content,
        pandoc.Plain({
          pandoc.Span(
            { pandoc.Str(resolved_attrs.title) },
            pandoc.Attr("", { "richmd-callout-title" })
          ),
        })
      )
    end
    for _, item in ipairs(block.content) do
      table.insert(body_content, item)
    end
    local body_div =
      pandoc.Div(body_content, pandoc.Attr("", { "richmd-callout-body" }))
    return pandoc.Div({ body_div }, pandoc.Attr("", classes))
  end,
}
