-- Generated by scripts/richmd-project — do not hand-edit.
-- Structural renderer paired with when.schema.json (richmd requires a
-- render function beside every block schema). Emits the block's rendered
-- slot anatomy using richmd's own shipped theme classes (ADR-0021).

return {
  render = function(block, resolved_attrs)
    local inner = {}
    table.insert(
      inner,
      pandoc.Div(
        { pandoc.Plain({ pandoc.Str("when") }) },
        pandoc.Attr("", { "richmd-clause-keyword" })
      )
    )
    for _, b in ipairs(block.content or {}) do
      table.insert(inner, b)
    end
    return pandoc.Div(
      inner,
      pandoc.Attr("", { "richmd-clause", "richmd-clause--when" })
    )
  end,
}
