-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule: the behavior fence. A clause must not name the
-- mechanism; the forbidden vocabulary is per-level and declared in
-- design_doc.behavior_contract.fence. PARTIAL enforcement by design: a
-- denylist raises the floor, the reviewer catches the rest.
local FENCE = {
  ["interface"] = { terms = { "css", "selector", "class name", "classname", "component", "controller", "presenter", "viewmodel", "view model", "repository", "dto", "http", "status code", "endpoint", "<div", "css class" }, patterns = { "#[%w_-]+", "%.[%a][%w_-]*%-[%w_-]+", "%f[%w]id=", "data%-testid" } },
  ["boundary"] = { terms = { "sql", "insert into", "select *", "table", "column", "queue", "topic", "http", "status code", "wire format", "json payload" }, patterns = {  } },
}
local is_clause = { given = true, when = true, ["then"] = true }
-- clause text: the block body flattened to a lowercase string
local function body_text(p)
  return string.lower(p.body_text or "")
end
-- The projection is DEPTH-FIRST POST-ORDER: a clause is emitted BEFORE the
-- behavior block that encloses it, so the enclosing level= is not known yet
-- when the clause is seen. Clauses therefore accumulate into a pending run,
-- and the fence is applied when the behavior block arrives and supplies the
-- level. Orphan clauses (no behavior parent) are the clause rule's finding,
-- not the fence's — the fence stays silent on them.
return {
  check = function(block_projections, add_error)
    local pending = {}
    for _, p in ipairs(block_projections) do
      if is_clause[p.kind] then
        table.insert(pending, p)
      elseif p.kind == "behavior" then
        local level = p.attrs and p.attrs.level
        if level and FENCE[level] then
          for _, c in ipairs(pending) do
            local text = body_text(c)
            -- id/selector SHAPES first: matched as Lua patterns against
            -- the ORIGINAL-case body, since an id is case-sensitive.
            for _, pat in ipairs(FENCE[level].patterns) do
              local hit = string.match(c.body_text or "", pat)
              if hit then
                add_error(
                  "rule:behavior-fence",
                  c.location,
                  "this " .. c.kind .. " clause names an implementation"
                    .. " identifier (\"" .. hit .. "\") in a level="
                    .. level .. " rule — state the observable outcome"
                    .. " instead. The test: will this wording need to"
                    .. " change if the implementation does?"
                )
              end
            end
            for _, term in ipairs(FENCE[level].terms) do
              if string.find(text, term, 1, true) then
                add_error(
                  "rule:behavior-fence",
                  c.location,
                  "this " .. c.kind .. " clause names the mechanism (\""
                    .. term .. "\") in a level=" .. level .. " rule —"
                    .. " state the observable outcome instead. The test:"
                    .. " will this wording need to change if the"
                    .. " implementation does?"
                )
              end
            end
          end
        end
        pending = {}
      else
        pending = {}
      end
    end
  end,
}
