-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule: behavior clause structure. The clause kinds are legal
-- only inside a behavior block; order is fixed; cardinality is declared in
-- design_doc.behavior_contract.clause_cardinality.
-- NOTE: `then` is a reserved Lua keyword, so every table key naming the
-- then-clause uses bracket syntax ["then"], never bare then=.
local CLAUSES = { "given", "when", "then" }
local ORDER = { given = 1, when = 2, ["then"] = 3 }
local is_clause = {}
for _, k in ipairs(CLAUSES) do is_clause[k] = true end
return {
-- The projection is DEPTH-FIRST POST-ORDER: a nested clause is emitted
-- BEFORE its enclosing behavior block. So clauses accumulate into a pending
-- run, and the next behavior block claims that run as its children. Any
-- other block kind between them ends the run, orphaning those clauses.
  check = function(block_projections, add_error)
    local pending = {}
    local function orphan_all()
      for _, c in ipairs(pending) do
        add_error(
          "rule:behavior-clauses",
          c.location,
          "a " .. c.kind .. " clause is legal only nested inside a"
            .. " behavior block"
        )
      end
      pending = {}
    end
    for _, p in ipairs(block_projections) do
      if is_clause[p.kind] then
        table.insert(pending, p)
      elseif p.kind == "behavior" then
        local counts = { given = 0, when = 0, ["then"] = 0 }
        local last_rank = 0
        for _, c in ipairs(pending) do
          counts[c.kind] = counts[c.kind] + 1
          local rank = ORDER[c.kind]
          if rank < last_rank then
            add_error(
              "rule:behavior-clauses",
              c.location,
              "clause order is fixed given -> when -> then; a " .. c.kind
                .. " clause appears after a later clause"
            )
          end
          last_rank = rank
        end
        if counts.when ~= 1 then
          add_error(
            "rule:behavior-clauses",
            p.location,
            "behavior rule has " .. tostring(counts.when)
              .. " when clause(s) — exactly one is required (two events"
              .. " are two rules)"
          )
        end
        if counts["then"] < 1 then
          add_error(
            "rule:behavior-clauses",
            p.location,
            "behavior rule has no then clause — at least one observable"
              .. " outcome is required"
          )
        end
        pending = {}
      else
        orphan_all()
      end
    end
    orphan_all()
  end,
}
