-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule (richmd#0008): the foundation blocks (goal, no-goal,
-- invariant, principle) appear in the schema-declared order, and the
-- per-kind minimum holds (>=1 goal, invariant, principle). Order + kinds
-- derive from schema/design-schema.json (foundation_cardinality /
-- spine[0], cross-checked); this file is regenerated from them.
local ORDER = { "goal", "no-goal", "invariant", "principle" }
local REQUIRED = { "goal", "invariant", "principle" }
local rank = {}
for i, k in ipairs(ORDER) do rank[k] = i end
return {
  check = function(block_projections, add_error)
    local seen_rank = 0
    local prev_kind = nil
    local counts = {}
    local last_location = "document"
    for _, p in ipairs(block_projections) do
      local r = rank[p.kind]
      if r ~= nil then
        last_location = p.location
        counts[p.kind] = (counts[p.kind] or 0) + 1
        if r < seen_rank then
          add_error(
            "rule:foundation-order-and-cardinality",
            p.location,
            "foundation kind '" .. p.kind .. "' appears after '"
              .. tostring(prev_kind) .. "' — section 00 orders its kinds "
              .. table.concat(ORDER, " -> ")
          )
        else
          seen_rank = r
          prev_kind = p.kind
        end
      end
    end
    -- cardinality only applies once the document HAS a foundation (any of
    -- the ordered kinds present); a document with none is not a design
    -- document this rule judges.
    local any = false
    for _, k in ipairs(ORDER) do if counts[k] then any = true end end
    if not any then return end
    for _, k in ipairs(REQUIRED) do
      if (counts[k] or 0) == 0 then
        add_error(
          "rule:foundation-order-and-cardinality",
          last_location,
          "the foundation requires at least one '" .. k .. "' block"
        )
      end
    end
  end,
}
