-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule (richmd#0008): an invariant block's enforcement attr
-- is one of the schema enforcement values, and a mechanism/partial
-- invariant names a script. The enum derives from
-- schema.enums.enforcement.values; regenerated from the schema.
local ENFORCEMENT = { "mechanism", "partial", "convention" }
local NAMES_SCRIPT = { "mechanism", "partial" }
local enf_ok = {}
for _, e in ipairs(ENFORCEMENT) do enf_ok[e] = true end
local needs_script = {}
for _, e in ipairs(NAMES_SCRIPT) do needs_script[e] = true end
return {
  check = function(block_projections, add_error)
    for _, p in ipairs(block_projections) do
      if p.kind == "invariant" then
        local e = p.attrs and p.attrs.enforcement
        if not e or not enf_ok[e] then
          add_error(
            "rule:invariant-enforcement",
            p.location,
            "invariant enforcement '" .. tostring(e) .. "' — required and "
              .. "one of " .. table.concat(ENFORCEMENT, ", ")
          )
        elseif needs_script[e] and not (p.attrs and p.attrs.script) then
          add_error(
            "rule:invariant-enforcement",
            p.location,
            "invariant enforcement=" .. e .. " without a script — a " .. e
              .. " invariant names the script that decides it (script=<name>)"
          )
        end
      end
    end
  end,
}
