-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule (richmd#0008): a `lens=` block attr may name a `+`
-- combo of lens members; each part must be a valid lens with no
-- duplicate. richmd validates single inline `lens:` spans natively but
-- never splits a `+` combo, and never validates a `lens=` attr at all,
-- so the attr combo is checked here. The lens set derives from
-- schema.enums.lens.values; regenerated from the schema.
local LENSES = { "modeling", "depth", "composition", "state", "invariants", "robustness" }
local lens_ok = {}
for _, l in ipairs(LENSES) do lens_ok[l] = true end
return {
  check = function(block_projections, add_error)
    for _, p in ipairs(block_projections) do
      local raw = p.attrs and p.attrs.lens
      if raw ~= nil then
        local seen = {}
        for part in string.gmatch(raw, "[^+]+") do
          if not lens_ok[part] then
            add_error(
              "rule:lens-combo",
              p.location,
              "unknown lens '" .. part .. "' in lens= attr — lenses: "
                .. table.concat(LENSES, ", ")
            )
          elseif seen[part] then
            add_error(
              "rule:lens-combo",
              p.location,
              "duplicate lens '" .. part .. "' in lens= combo"
            )
          else
            seen[part] = true
          end
        end
      end
    end
  end,
}
