-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule (richmd#0008): each pending block carries a valid kind
-- and a YYYY-MM-DD since, and a build entry cites an ADR. kind vocabulary
-- derives from schema.pending_ledger.kinds; regenerated from the schema.
--
-- The ADR citation is checked against the block's LINKS (richmd#21): a
-- build entry must carry a link whose resolved target fragment matches
-- `#adr-NNNN` — an actual link, not merely visible text. This matches the
-- in-house validator's href-fragment strictness.
local KINDS = { "build", "verify", "foundation", "ruling" }
local kind_ok = {}
for _, k in ipairs(KINDS) do kind_ok[k] = true end
return {
  check = function(block_projections, add_error)
    for _, p in ipairs(block_projections) do
      if p.kind == "pending" then
        local k = p.attrs and p.attrs.kind
        if not k or not kind_ok[k] then
          add_error(
            "rule:pending-entry-validity",
            p.location,
            "pending kind '" .. tostring(k) .. "' — kind is required and "
              .. "one of " .. table.concat(KINDS, ", ")
          )
        end
        local since = p.attrs and p.attrs.since
        if not since or not string.match(since, "^%d%d%d%d%-%d%d%-%d%d$") then
          add_error(
            "rule:pending-entry-validity",
            p.location,
            "pending since '" .. tostring(since) .. "' — since is required "
              .. "as YYYY-MM-DD"
          )
        end
        if k == "build" then
          local cited = false
          for _, link in ipairs(p.links or {}) do
            local target = link.target or ""
            if string.match(string.lower(target), "#adr%-%d%d%d%d") then
              cited = true
            end
          end
          if not cited then
            add_error(
              "rule:pending-entry-validity",
              p.location,
              "pending build entry must cite its ADR (a link whose target "
                .. "fragment is #adr-NNNN)"
            )
          end
        end
      end
    end
  end,
}
