-- Generated by scripts/richmd-project — do not hand-edit.
-- Cross-block rule: a titled block's title= attr is at most 64 chars
-- (the statement_blocks contract cap). Presence + type are enforced by the
-- block schema; this rule adds the length cap. Titled kinds derive from the
-- schema (blocks declaring a required title attr).
local TITLED = { "behavior", "goal", "invariant", "no-goal", "pending", "principle" }
local titled_ok = {}
for _, k in ipairs(TITLED) do titled_ok[k] = true end
return {
  check = function(block_projections, add_error)
    for _, p in ipairs(block_projections) do
      if titled_ok[p.kind] then
        local t = p.attrs and p.attrs.title
        if t and utf8 and utf8.len and utf8.len(t) and utf8.len(t) > 64 then
          add_error(
            "rule:title-length",
            p.location,
            "title is " .. tostring(utf8.len(t)) .. " chars — the "
              .. p.kind .. " title= must be at most 64"
          )
        end
      end
    end
  end,
}
